name: WarpPortalCommands
main: me.wpc.main
version: 1.3
commands:
  set-warp-portal-command:
    description: Sets and adds commands to run when walking through warp portals.
    aliases: [swpc,awpc]
  del-warp-portal-command:
    description: Delete commands from warp portals.
    aliases: dwpc
  list-warp-portal-command:
    description: Delete commands from warp portals.
    aliases: [lwpc,view-warp-portal-command,vwpc]
  set-warp-portal-price:
    description: Sets the price for a warp portal.
    aliases: [swpp,setwpp]
  wpc:
    description: Basic command for WarpPortalCommands.